import "moment/locale/pt-br";
import LocalizedStrings from "localized-strings";

const strings = new LocalizedStrings({
	ptBR: {
		removeCharactersExceptLetterNumber: (character: string) => character.replace(/[^a-zA-Z0-9]/g, ""),
		components: {
			editProfile: {
				success: "Editado com sucesso",
			},
			imagePicker: {
				selectAnImage: "Selecione uma imagem",
			},
		},
		nav: {
			home: "Home",
			restaurants: "Restaurantes",
			users: "Users",
			logout: "Sair",
		},
		actions: {
			save: "Salvar",
			delete: "Apagar",
			create: "Criar",
			cancel: "Cancelar",
			select: "Selecionar",
			back: "Voltar",
			add: "Adicionar",
			send: "Enviar",
		},
		moment: {
			day: "DD",
			dateMonth: "DD/MM",
			date: "DD/MM/YYYY",
			dateHour: "DD/MM/YYYY HH[h]",
			dateTime: "DD/MM/YYYY HH:mm",
		},
		error: {
			stillLoading: "Ainda Carregando, aguarde.",
			notLoggedIn: "Usuario não logado",
			default: "Houve um erro, tente novamente mais tarde.",
		},
		common: {
			noResutls: "Sem Resultados",
			delete: "Clique para deletar",
			disable: "Clique para desabilitar",
			enable: "Clique para habilitar",
			details: "Clique para ver mais informações",
			edit: "Clique para editar",
			cancel: "Cancelar",
			finish: "Finalizar",
			confirm: "Confirmar",
			detailsTitle: "Detalhes",
			editTitle: "Editar",
			send: "Enviar",
			buttons: {
				confirmButton: (isEdit?: boolean) => isEdit ? "Editar" : "Enviar",
				backButton: "Voltar",
			},
			empty: "Vazio",
			fields: {
				name: "Nome:",
				corporateName: "Nome corporativo:",
				email: "E-mail:",
				photo: "Foto:",
				phone: "Celular:",
				documentNumber: "CNPJ: ",
				zipcode: "CEP:",
				street: "Rua:",
				streetNumber: "Número:",
				complementary: "Complemento:",
				neighborhood: "Bairro:",
				city: "Cidade:",
				countryCode: "Código do País:",
				state: "Estado:",
			},
			mask: {
				date: "__/__/____",
				time: "__:__",
			},
			modal: {
				title: "Deletar",
				description: (itemName: string) => `Tem certeza que deseja deletar ${itemName}?`,
				descriptionRemove: (itemName: string) => `Tem certeza que deseja remover ${itemName}?`,
				button: {
					remove: "Remover",
					delete: "Deletar",
					cancel: "Cancelar",
				},
			},
		},
		login: {
			loginIn: "Login",
			recoveryPassword: "Recuperar Senha",
			success: (userName: string) => `Bem vindo ${userName}.`,
			fields: {
				email: "E-mail",
				password: "Senha",
			},
		},
		recoveryPage: {
			success: "Bem vindo!",
			title: "Recuperação de Senha",
			newAccess: "Novo Acesso",
			sendSuccess: "E-mail enviado com sucesso!",
			recoverPasswordButton: "Enviar e-mail",
			newPasswordButton: "Alterar Senha",
			email: "Email",
			token: "Token",
			validToken: "Token válido!",
			confirmTokenButton: "Confirmar Token",
			tokenButton: "Já possui um token?",
			noTokenButton: "Não possuo token",
			newPassword: "Nova senha",
			confirmNewPassword: "Confirme sua nova senha",
			samePasswordError: "As senhas não correspondem",
		},
		users: {
			table: {
				title: "Lista de Usuários",
				header: ["", "Usuários", "Email", "Data de Cadastro" ],
				delete: (userName: string) => `Usuário ${userName} foi deletado!`,
			},
			edit: {
				title: "Edição de Usuário",
				success: "Usuário editado com sucesso",
			},
		},
		restaurants: {
			autocompleteLabel: "Restaurante:",
			autocompletePlaceholder: "Pesquisar restaurantes",
			totalText: "Restaurantes cadastrados",
			table: {
				title: "Lista Usuários do Restaurante",
				header:  ["", "Nome do Restaurante", "Documento do Restaurante", "Data de Cadastro"],
				delete: (userName: string) => `Restaurante ${userName} foi deletado!`,
				addButtonText: "Adicionar novo Restaurante",
				totalText: "Restaurantes cadastrados",
			},
			createOrEdit: {
				title: (isEdit?: boolean) => isEdit ? "Edição de Restaurante" : "Cadastro de Restaurante",
				success: (isEdit?: boolean) => isEdit ? "Restaurante editada com sucesso" : "Restaurante criada com sucesso",
				address: "Endereço",
				helperServiceDays: "(dias da semana e horário):",
				errorAddress: "Erro no preenchimento do endereço.",
				documents: [
					"Contrato Social",
					"CNPJ Atualizado",
					"CCM ou ISS junto à prefeitura",
					"CNES",
					"Comprovante do pagamento do ISS",
					"Comprovante do pagamento da taxa de fiscalização do estabelecimento",
					"Alvará de funcionamento e vigilância sanitária atualizados",
					"Currículo completo de todos os profissionais que trabalham na restaurante (com o título de especialista)",
					"Comprovante de conta bancária",
				],
				documentsTitle: "Documentos",
				bankAccountTitle: (hasBankAccount: boolean) => hasBankAccount ? "Editar Conta Bancária" : "Cadastro de Conta",
				banckAccount: "Conta Bancária:",
				successBankAccount: (isEdit?: boolean) => isEdit ? "Conta editada com sucesso" : "Conta Bancária criada com sucesso",
			},
			modal: {
				title: "Desabilitar Restaurante",
				description: (itemName: string, isRestaurantBlocked: boolean) => `Tem certeza que deseja ${isRestaurantBlocked ? "habilitar" : "desabilitar"} ${itemName}?`,
				button: {
					disable: "Desabilitar",
					enable: "Habilitar",
					cancel: "Cancelar",
				},
			},
		},
	},

});

export default strings;
