stages:
    - test
    - build
    - deploy
    - caddyfile

before_script:
    - export PROJECT_NAME=$(echo ${CI_PROJECT_NAME//-/ } | awk '{print $1}')
    - export BRANCH_PREFIX=$(if [ $CI_COMMIT_REF_NAME == "master" ]; then echo ""; else echo "$CI_COMMIT_REF_NAME."; fi;)
    - export WEB_URL="$BRANCH_PREFIX""dashboard.iklub.startapp.one"

"[Linter] Type Check":
    image: $CI_REGISTRY/startapp-one/developers/es-linter
    stage: test
    script:
      - yarn install
      - yarn code-check

"[Build] React":
    image: node:14
    stage: build
    only:
        - master
        - staging
        - develop
    script:
        - yarn install
        - "if [ $CI_COMMIT_REF_NAME == master ]; then export NODE_ENV=production; else export NODE_ENV=$CI_COMMIT_REF_NAME; fi;"
        - NODE_ENV=$NODE_ENV yarn run build
    artifacts:
        paths:
            - dist/

"[Upload] React":
    image: $CI_REGISTRY/startapp-one/maintainers/minio-client
    stage: deploy
    only:
        - master
        - staging
        - develop
    script:
        - mc mb startapp/$PROJECT_NAME/ || true
        - mc cp -r dist/ startapp/$PROJECT_NAME/$WEB_URL/

"[Upload] Caddyfile":
    image: $CI_REGISTRY/startapp-one/maintainers/minio-client
    stage: caddyfile
    only:
        - master
    script:
        - mc cp deploy/Caddyfile startapp/caddy/sites/$CI_PROJECT_NAME.conf
